receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto
#
#  otlp/jaeger:
#    endpoint: jaeger-all-in-one:4317
#    tls:
#      insecure: true
#
#  otlp/tempo:
#    endpoint: tempo:4317
#    tls:
#      insecure: true

extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector's performance data
  pprof:
  # serves as a http endpoint that provides live debugging data about instrumented components
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]