spring:
  application:
    name: d2csgame
  profiles:
    active: dev
  mail:
    from: ${MAIL_FROM:tuyenlam987@gmail.com}
    port: 587
    host: smtp.gmail.com
    username: tuyenlam987@gmail.com
    password: hrbn jrsp ilkr gqwu
    properties:
      mail:
        smtp:
          auth: true
          from: tuyenlam987@gmail.com
          ssl:
            enable: false
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
    default-encoding: UTF-8
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 200
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8080
file:
  upload-dir:
    product: D://upload/product/
management:
  endpoints:
    web:
      exposure:
        include: health
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:4318/v1/metrics
#        step: 10s
  health:
    mail:
      enabled: false
vnpay:
  vnp_TmnCode: ${TMN_CODE:6HR41JF1}
  vnp_HashSecret: ${SECRET_KEY:KTM41MMP5HBWDRO1P7Z7HYK35HMBH8I1}
  vnp_PayUrl: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  vnp_ReturnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
  vnp_OrderType: ${ORDER_TYPE:other}
  vnp_Command: ${COMMAND:pay}
  vnp_Version: ${VERSION:2.1.0}
  management:
    address: https://sandbox.vnpayment.vn/merchantv2/
    username: ${VNPAY_USERNAME:lam.shsoftvina@gmail.com}
    password: ${VNPAY_PASSWORD:Tuyenlam1012}
  IPN:
    SIT: https://sandbox.vnpayment.vn/vnpaygw-sit-testing/user/login
    username: ${VNPAY_USERNAME:lam.shsoftvina@gmail.com}
    password: ${VNPAY_PASSWORD:Tuyenlam1012}
