spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/d2csgame?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
  jpa:
    hibernate:
      ddl-auto: update  # Có thể là create, create-drop, validate, hoặc none
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Định dạng câu lệnh SQL
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 20MB