spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
#    username: ${MYSQL_USER:root}
#    password: ${MYSQL_PASSWORD:admin}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/d2csgame?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
  jpa:
    hibernate:
      ddl-auto: update  # Có thể là create, create-drop, validate, hoặc none
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Định dạng câu lệnh SQL
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 20MB
  security:
    jwt:
      secret: AIsCx24wtFSn3A2ZQ7M93pPNWE7sS7n2Y2ApAdmX1xHBe3XFsnzi0bqCLkdjDy7jZ6TFMibS6WgXNwA8aF9lDg==
      expiration: 86400000 # Hết hạn access token là 24 giờ
      refreshExpiration: 2592000000 # Hết hạn refresh là 30 ngày